### ISSUE TITLE
bootstrap/config.yaml: No such file or directory

### ISSUE THREAD

**Issue by oavioz** [yuvipanda/acs-jupyterhub#6]
Thanks for great repo!

After 10 min of deploy(deploy.py) running i'm getting the following error:

demouser@Ubuntu16:~/acs-jupyterhub$ ./deploy.py -s 9xxxdac2-b5xx-4c3a-8159-9ee21axxxf0 -n k8s-es5 -d 2 -D 110
INFO[0000] Generating assets...
Warning: Permanently added 'k8s-es5.westus2.cloudapp.azure.com,52.247.214.71' (ECDSA) to the list of known hosts.
Warning: Permanently added 'k8s-es5.westus2.cloudapp.azure.com,52.247.214.71' (ECDSA) to the list of known hosts.
bootstrap/config.yaml: No such file or directory
setup.bash                                                                                                           100%  553     0.5KB/s   00:00
Traceback (most recent call last):
  File "./deploy.py", line 143, in <module>
    sp.check_call(cmd)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['scp', '-i', 'k8s-es5/id_rsa', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'StrictHostKeyChecking=no', '-o', 'User=datahub', 'bootstrap/config.yaml', 'bootstrap/setup.bash', 'k8s-es5.westus2.cloudapp.azure.com:']' returned non-zero exit status 1

Can you check the git repo and upload config.yaml?
BTW, i found another issues with vmSize. "Standard_D4s_v3" are not supported on ACS. i changed it to "Standard_DS4_v2" and the error disappeared.

Waiting for help.

Thanks!

**Comment by oavioz** [comment]
Note that "scale-up.py" is not an executed file. should be change the permission mod. chmod 755 scale-up.py?

Thanks

**Comment by yuvipanda** [comment]
Thanks for opening an issue! Me and @ryanlovett are both at JupyterCon this week, so our responses will be slower :( hopefully we'll get to it next week!

You don't need config.yaml, so you can just get rid of it in the python script if you wanna.

**Comment by yuvipanda** [comment]
I just pushed a fix

**Comment by oavioz** [comment]
Hello Yuni,

I'm getting error on command line "verify ssh works"
Note that i printed the ssh command and ran it manually and it it
working(ssh login to master)

command print:(working from my host)
ssh -i myclustername/id_rsa -o UserKnownHostsFile=/dev/null -o
StrictHostKeyChecking=no -o User=useradmin
myclustername.westeurope.cloudapp.azure.com

command error from deploy.sp: failed!!

demouser@Ubuntu16Dev:~/acs-jupyterhub$ ./deploy.py -s
xxxxdac2-b53c-xx3a-8159-9eexxx9f08f0 -n myclustername
Retrying role assignment creation: 1/36
INFO[0000] Generating assets...
verify ssh works cmd: ['ssh', '-i', 'myclustername/id_rsa', '-o',
'UserKnownHostsFile=/dev/null', '-o', 'StrictHostKeyChecking=no', '-o',
'User=useradmin', 'myclustername.westeurope.cloudapp.azure.com', 'true']
Warning: Permanently added
'myclustername.westeurope.cloudapp.azure.com,40.68.254.189'
(ECDSA) to the list of known hosts.
System is going down.

Connection to myclustername.westeurope.cloudapp.azure.com closed by remote
host.
Traceback (most recent call last):
File "./deploy.py", line 111, in
sp.check_call(cmd)
File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ssh', '-i',
'myclustername/id_rsa', '-o', 'UserKnownHostsFile=/dev/null', '-o',
'StrictHostKeyChecking=no', '-o', 'User=useradmin', '
myclustername.westeurope.cloudapp.azure.com', 'true']' returned non-zero
exit status 255

Any help what is the different? and what is the error?


Note: opened this issues on your repo.

Thanks,

Oshik.

**Comment by oavioz** [comment]
Hi again,

I have to that it is working sporadically. now i ran again and it finished
successful.
Maybe it is an issues of timeout? maybe we should add a sleep command?

Thanks,
Oshik.
