### ISSUE TITLE
PLAY [nfs_servers]  ERROR

### ISSUE THREAD

**Issue by oavioz** [yuvipanda/acs-jupyterhub#8]
hi,

Any help why i failed on PLAY [nfs_servers]?

Thanks.
Error:
demouser@Ubuntu16Dev:~/acs-jupyterhub$ ./deploy.py -s 9xxxxxc2-bxxx-4c3a-81x9-9ee21xxf08f0 -n k8s-es5-3 -d 2 -D 134
Retrying role assignment creation: 1/36
INFO[0000] Generating assets...
Warning: Permanently added 'k8s-es5-3.westus2.cloudapp.azure.com,52.247.209.8' (ECDSA) to the list of known hosts.
Warning: Permanently added 'k8s-es5-3.westus2.cloudapp.azure.com,52.247.209.8' (ECDSA) to the list of known hosts.
setup.bash                                                                       100%  553     0.5KB/s   00:00
.ansible.cfg                                                                     100%   37     0.0KB/s   00:00
Warning: Permanently added 'k8s-es5-3.westus2.cloudapp.azure.com,52.247.209.8' (ECDSA) to the list of known hosts.
Cloning into 'k8s-nfs-ansible'...
Warning: Permanently added 'k8s-es5-3.westus2.cloudapp.azure.com,52.247.209.8' (ECDSA) to the list of known hosts.
id_rsa                                                                           100% 1675     1.6KB/s   00:00
id_rsa.pub                                                                       100%  402     0.4KB/s   00:00
Warning: Permanently added 'k8s-es5-3.westus2.cloudapp.azure.com,52.247.209.8' (ECDSA) to the list of known hosts.
gpg: keyring `/tmp/tmphdnvj8dz/secring.gpg' created
gpg: keyring `/tmp/tmphdnvj8dz/pubring.gpg' created
gpg: requesting key 7BB9C367 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmphdnvj8dz/trustdb.gpg: trustdb created
gpg: key 7BB9C367: public key "Launchpad PPA for Ansible, Inc." imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

PLAY [nfs_servers] *************************************************************

TASK [Gathering Facts] *********************************************************
fatal: [nfsserver]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Host key verification failed.\r\n", "unreachable": true}
        to retry, use: --limit @/home/datahub/k8s-nfs-ansible/playbook.retry

PLAY RECAP *********************************************************************
nfsserver                  : ok=0    changed=0    unreachable=1    failed=0

Traceback (most recent call last):
  File "./deploy.py", line 155, in <module>
    sp.check_call(cmd)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ssh', '-i', 'k8s-es5-3/id_rsa', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'StrictHostKeyChecking=no', '-o', 'User=datahub', 'k8s-es5-3.westus2.cloudapp.azure.com', 'sudo bash bootstrap/setup.bash k8s-es5-3']' returned non-zero exit status 1

**Comment by oavioz** [comment]
Note that i tried to reproduce the error by connecting manually to the master and then running the following command:

datahub@k8s-master-30868763-0:~$ sudo bash bootstrap/setup.bash k8s-es5-3
gpg: keyring `/tmp/tmpvqce26ad/secring.gpg' created
gpg: keyring `/tmp/tmpvqce26ad/pubring.gpg' created
gpg: requesting key 7BB9C367 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpvqce26ad/trustdb.gpg: trustdb created
gpg: key 7BB9C367: public key "Launchpad PPA for Ansible, Inc." imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

PLAY [nfs_servers] ***************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************
The authenticity of host 'nfsserver (10.240.0.7)' can't be established.
ECDSA key fingerprint is SHA256:DV0o72nVqF1v5P3QSQgapbf2anEXxFt2kDZOr8pPr6c.
Are you sure you want to continue connecting (yes/no)? yes
ok: [nfsserver]

TASK [install zfsutils-linux] ****************************************************************************************************
ok: [nfsserver]

TASK [install nfs server packages] ***********************************************************************************************
changed: [nfsserver]

TASK [add mount path to /etc/exports] ********************************************************************************************
changed: [nfsserver]

TASK [create zfs filesystem] *****************************************************************************************************
changed: [nfsserver]

TASK [gather zfs facts] **********************************************************************************************************
ok: [nfsserver]

TASK [check if zfs dataset is mounted] *******************************************************************************************
skipping: [nfsserver] => (item={u'setuid': u'on', u'relatime': u'off', u'referenced': u'96K', u'logicalused': u'40K', u'zoned': u'off', u'primarycache': u'all', u'logbias': u'latency', u'creation': u'Mon Aug 28 14:32 2017', u'sync': u'standard', u'snapdev': u'hidden', u'dedup': u'off', u'sharenfs': u'off', u'acltype': u'off', u'sharesmb': u'off', u'canmount': u'on', u'mountpoint': u'/export/pool0/homes', u'casesensitivity': u'sensitive', u'utf8only': u'off', u'usedbysnapshots': u'0', u'defcontext': u'none', u'rootcontext': u'none', u'mounted': u'yes', u'compression': u'off', u'snapdir': u'hidden', u'overlay': u'off', u'xattr': u'on', u'exec': u'on', u'copies': u'1', u'snapshot_limit': u'none', u'aclinherit': u'restricted', u'compressratio': u'1.00x', u'readonly': u'off', u'version': u'5', u'recordsize': u'128K', u'filesystem_limit': u'none', u'type': u'filesystem', u'secondarycache': u'all', u'refreservation': u'none', u'available': u'129G', u'used': u'96K', u'written': u'96K', u'refquota': u'none', u'refcompressratio': u'1.00x', u'quota': u'none', u'snapshot_count': u'none', u'fscontext': u'none', u'vscan': u'off', u'reservation': u'none', u'usedbyrefreservation': u'0', u'atime': u'on', u'normalization': u'none', u'usedbychildren': u'0', u'usedbydataset': u'96K', u'name': u'pool0/homes', u'mlslabel': u'none', u'redundant_metadata': u'all', u'filesystem_count': u'none', u'devices': u'on', u'logicalreferenced': u'40K', u'context': u'none', u'checksum': u'on', u'nbmand': u'off'})

TASK [create mount path directory] ***********************************************************************************************
ok: [nfsserver]

TASK [set permissions on /export] ************************************************************************************************
changed: [nfsserver]

TASK [export filesystem] *********************************************************************************************************
changed: [nfsserver]

PLAY [nfs_clients] ***************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************
The authenticity of host 'k8s-master-30868763-0 (10.240.255.5)' can't be established.
ECDSA key fingerprint is SHA256:ZGQYbw8c+2HaVXZkEGjPnA/ZqWHo3F/GL8wv5wh9LtE.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'k8s-master-30868763-1 (10.240.255.6)' can't be established.
ECDSA key fingerprint is SHA256:hgfFKYPerkyRG6qGTdMZVjnQMyHF+ZmLXqGpVYkI8oU.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'k8s-pool1-30868763-1 (10.240.0.5)' can't be established.
ECDSA key fingerprint is SHA256:J38QSk0kk6OqTwP5NzoGVl19UPfpoX+sL4mTI2ftdbc.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'k8s-master-30868763-2 (10.240.255.7)' can't be established.
ECDSA key fingerprint is SHA256:aU7srVuxtqPUxk7otYMFVX1LkUm6SGbWAkjYXuw4JmQ.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'k8s-pool1-30868763-0 (10.240.0.6)' can't be established.
ECDSA key fingerprint is SHA256:17NISRiYtleUuGeSI4mNcIXxJ5xWzOo3ZGT93gFRTJc.
Are you sure you want to continue connecting (yes/no)? yes
ok: [k8s-master-30868763-0]
The authenticity of host 'k8s-pool1-30868763-2 (10.240.0.4)' can't be established.
ECDSA key fingerprint is SHA256:JnxYbHUNQC85b2hCIhNTIbg4fJAZtwtNtc4LleOrQbY.
Are you sure you want to continue connecting (yes/no)? yes
ok: [k8s-master-30868763-1]

fatal: [k8s-pool1-30868763-1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Host key verification failed.\r\n", "unreachable": true}

fatal: [k8s-master-30868763-2]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Host key verification failed.\r\n", "unreachable": true}

fatal: [k8s-pool1-30868763-0]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Host key verification failed.\r\n", "unreachable": true}

fatal: [k8s-pool1-30868763-2]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Host key verification failed.\r\n", "unreachable": true}

TASK [install nfs client packages] ***********************************************************************************************

changed: [k8s-master-30868763-0]
changed: [k8s-master-30868763-1]

TASK [create mount path] *********************************************************************************************************
changed: [k8s-master-30868763-1]
changed: [k8s-master-30868763-0]

TASK [mount nfs filesystem] ******************************************************************************************************
changed: [k8s-master-30868763-0]
changed: [k8s-master-30868763-1]

TASK [make /data] ****************************************************************************************************************
changed: [k8s-master-30868763-0]
changed: [k8s-master-30868763-1]

TASK [make symlink to /data/homes] ***********************************************************************************************
changed: [k8s-master-30868763-0]
changed: [k8s-master-30868763-1]
        to retry, use: --limit @/home/datahub/k8s-nfs-ansible/playbook.retry

PLAY RECAP ***********************************************************************************************************************
k8s-master-30868763-0      : ok=6    changed=5    unreachable=0    failed=0
k8s-master-30868763-1      : ok=6    changed=5    unreachable=0    failed=0
k8s-master-30868763-2      : ok=0    changed=0    unreachable=1    failed=0
k8s-pool1-30868763-0       : ok=0    changed=0    unreachable=1    failed=0
k8s-pool1-30868763-1       : ok=0    changed=0    unreachable=1    failed=0
k8s-pool1-30868763-2       : ok=0    changed=0    unreachable=1    failed=0
nfsserver                  : ok=9    changed=5    unreachable=0    failed=0
